name: Docker Image CI

on:
  push:
    branches: [ "dev" ]

env:
  IMAGE_NAME: gttfe-2

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v4
      with: 
        lfs: 'true'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build app
      run: npm ci && npm run build
      env:
        NODE_OPTIONS: --openssl-legacy-provider
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin      
    - name: Push image
      run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:testing
          docker push --all-tags $IMAGE_ID
