name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: gttfe-2

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v4
      with: 
        lfs: 'true'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build app
      run: npm ci && npm run build
      env:
        NODE_OPTIONS: --openssl-legacy-provider
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin      
    - name: Build and push the Docker image
      run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker buildx build . --platform linux/amd64,linux/arm64 --file Dockerfile --tag $IMAGE_ID:latest --tag $IMAGE_ID:stable --tag $IMAGE_ID:$VERSION --label "runnumber=${GITHUB_RUN_ID}" --push

